// ============ Firebase Configuration ============
const FIREBASE_CONFIG = {
    apiKey: "AIzaSyDRlGps4_dqRBJ2SYmbeXtdDRGTIvYQ510",
    authDomain: "serviconnect-446dd.firebaseapp.com",
    projectId: "serviconnect-446dd",
    storageBucket: "serviconnect-446dd.firebasestorage.app",
    messagingSenderId: "102078290806",
    appId: "1:102078290806:web:88a6e1f9908100a3253857"
};

// ============ Cloudinary Configuration ============
const CLOUDINARY_CONFIG = {
    cloudName: "serviconnect",
    uploadPreset: "connect",
    apiEndpoint: "https://api.cloudinary.com/v1_1/serviconnect/image/upload",
    videoEndpoint: "https://api.cloudinary.com/v1_1/serviconnect/video/upload"
};

// ============ Backend URL ============
const BACKEND_URL = "https://connect-backend--serviconnect9.replit.app";

// ============ Flutterwave Public Key ============
const FLUTTERWAVE_PUBLIC_KEY = "FLWPUBK-b5d5cb8f23411dc9c84afd34c839c15b-X";

// ============ Admin Email ============
const ADMIN_EMAIL = "ebubechichukwu8@gmail.com";

// ============ WhatsApp Community Link ============
const WHATSAPP_COMMUNITY_LINK = "https://whatsapp.com/channel/0029VbClcrq11ulFYHVcU63m";

// ============ Platform Constants ============
const PLATFORM_CONFIG = {
    merchantSubscriptionPrice: 2,
    affiliateSubscriptionPrice: 3,
    minDeposit: 5,
    maxDeposit: 10000,
    minWithdrawal: 5,
    maxWithdrawal: 10000,
    maxWithdrawalsPerDay: 2,
    baseCurrency: "USD",
    supportedCountries: 180,
    maxProductImages: 5,
    maxSuspensionsBeforeBan: 3,
    commissionHoldDays: 7,
    appName: "Shoplify",
    appVersion: "1.0.0",
    poweredBy: "Rev"
};

// ============ Product Categories ============
const CATEGORIES = [
    "Fashion", "Shoes", "Electronics", "Bags", "Beauty",
    "Watches", "Accessories", "Home & Garden", "Sports", "Toys"
];

// ============ Store Templates ============
const STORE_TEMPLATES = [
    { id: "classic", name: "Classic", color: "#1A1A2E", icon: "🏪", description: "Clean and professional" },
    { id: "modern", name: "Modern", color: "#FFFFFF", icon: "🛍️", description: "Sleek modern design" },
    { id: "premium", name: "Premium", color: "#FFD700", icon: "✨", description: "Luxury premium feel" },
    { id: "minimal", name: "Minimal", color: "#F5F5F5", icon: "📦", description: "Simple and elegant" }
];

// ============ 180 COUNTRIES WITH CURRENCIES & FLAGS ============
const COUNTRIES = [
    { code: "AF", name: "Afghanistan", currency: "AFN", flag: "🇦🇫", symbol: "؋" },
    { code: "AL", name: "Albania", currency: "ALL", flag: "🇦🇱", symbol: "L" },
    { code: "DZ", name: "Algeria", currency: "DZD", flag: "🇩🇿", symbol: "د.ج" },
    { code: "AD", name: "Andorra", currency: "EUR", flag: "🇦🇩", symbol: "€" },
    { code: "AO", name: "Angola", currency: "AOA", flag: "🇦🇴", symbol: "Kz" },
    { code: "AG", name: "Antigua and Barbuda", currency: "XCD", flag: "🇦🇬", symbol: "$" },
    { code: "AR", name: "Argentina", currency: "ARS", flag: "🇦🇷", symbol: "$" },
    { code: "AM", name: "Armenia", currency: "AMD", flag: "🇦🇲", symbol: "֏" },
    { code: "AU", name: "Australia", currency: "AUD", flag: "🇦🇺", symbol: "$" },
    { code: "AT", name: "Austria", currency: "EUR", flag: "🇦🇹", symbol: "€" },
    { code: "AZ", name: "Azerbaijan", currency: "AZN", flag: "🇦🇿", symbol: "₼" },
    { code: "BS", name: "Bahamas", currency: "BSD", flag: "🇧🇸", symbol: "$" },
    { code: "BH", name: "Bahrain", currency: "BHD", flag: "🇧🇭", symbol: ".د.ب" },
    { code: "BD", name: "Bangladesh", currency: "BDT", flag: "🇧🇩", symbol: "৳" },
    { code: "BB", name: "Barbados", currency: "BBD", flag: "🇧🇧", symbol: "$" },
    { code: "BY", name: "Belarus", currency: "BYN", flag: "🇧🇾", symbol: "Br" },
    { code: "BE", name: "Belgium", currency: "EUR", flag: "🇧🇪", symbol: "€" },
    { code: "BZ", name: "Belize", currency: "BZD", flag: "🇧🇿", symbol: "$" },
    { code: "BJ", name: "Benin", currency: "XOF", flag: "🇧🇯", symbol: "Fr" },
    { code: "BT", name: "Bhutan", currency: "BTN", flag: "🇧🇹", symbol: "Nu." },
    { code: "BO", name: "Bolivia", currency: "BOB", flag: "🇧🇴", symbol: "Bs." },
    { code: "BA", name: "Bosnia", currency: "BAM", flag: "🇧🇦", symbol: "KM" },
    { code: "BW", name: "Botswana", currency: "BWP", flag: "🇧🇼", symbol: "P" },
    { code: "BR", name: "Brazil", currency: "BRL", flag: "🇧🇷", symbol: "R$" },
    { code: "BN", name: "Brunei", currency: "BND", flag: "🇧🇳", symbol: "$" },
    { code: "BG", name: "Bulgaria", currency: "BGN", flag: "🇧🇬", symbol: "лв" },
    { code: "BF", name: "Burkina Faso", currency: "XOF", flag: "🇧🇫", symbol: "Fr" },
    { code: "BI", name: "Burundi", currency: "BIF", flag: "🇧🇮", symbol: "Fr" },
    { code: "CV", name: "Cabo Verde", currency: "CVE", flag: "🇨🇻", symbol: "$" },
    { code: "KH", name: "Cambodia", currency: "KHR", flag: "🇰🇭", symbol: "៛" },
    { code: "CM", name: "Cameroon", currency: "XAF", flag: "🇨🇲", symbol: "Fr" },
    { code: "CA", name: "Canada", currency: "CAD", flag: "🇨🇦", symbol: "$" },
    { code: "CF", name: "Central African Republic", currency: "XAF", flag: "🇨🇫", symbol: "Fr" },
    { code: "TD", name: "Chad", currency: "XAF", flag: "🇹🇩", symbol: "Fr" },
    { code: "CL", name: "Chile", currency: "CLP", flag: "🇨🇱", symbol: "$" },
    { code: "CN", name: "China", currency: "CNY", flag: "🇨🇳", symbol: "¥" },
    { code: "CO", name: "Colombia", currency: "COP", flag: "🇨🇴", symbol: "$" },
    { code: "KM", name: "Comoros", currency: "KMF", flag: "🇰🇲", symbol: "Fr" },
    { code: "CG", name: "Congo", currency: "XAF", flag: "🇨🇬", symbol: "Fr" },
    { code: "CR", name: "Costa Rica", currency: "CRC", flag: "🇨🇷", symbol: "₡" },
    { code: "CI", name: "Côte d'Ivoire", currency: "XOF", flag: "🇨🇮", symbol: "Fr" },
    { code: "HR", name: "Croatia", currency: "EUR", flag: "🇭🇷", symbol: "€" },
    { code: "CU", name: "Cuba", currency: "CUP", flag: "🇨🇺", symbol: "$" },
    { code: "CY", name: "Cyprus", currency: "EUR", flag: "🇨🇾", symbol: "€" },
    { code: "CZ", name: "Czech Republic", currency: "CZK", flag: "🇨🇿", symbol: "Kč" },
    { code: "DK", name: "Denmark", currency: "DKK", flag: "🇩🇰", symbol: "kr" },
    { code: "DJ", name: "Djibouti", currency: "DJF", flag: "🇩🇯", symbol: "Fr" },
    { code: "DM", name: "Dominica", currency: "XCD", flag: "🇩🇲", symbol: "$" },
    { code: "DO", name: "Dominican Republic", currency: "DOP", flag: "🇩🇴", symbol: "$" },
    { code: "EC", name: "Ecuador", currency: "USD", flag: "🇪🇨", symbol: "$" },
    { code: "EG", name: "Egypt", currency: "EGP", flag: "🇪🇬", symbol: "£" },
    { code: "SV", name: "El Salvador", currency: "USD", flag: "🇸🇻", symbol: "$" },
    { code: "GQ", name: "Equatorial Guinea", currency: "XAF", flag: "🇬🇶", symbol: "Fr" },
    { code: "ER", name: "Eritrea", currency: "ERN", flag: "🇪🇷", symbol: "Nfk" },
    { code: "EE", name: "Estonia", currency: "EUR", flag: "🇪🇪", symbol: "€" },
    { code: "SZ", name: "Eswatini", currency: "SZL", flag: "🇸🇿", symbol: "L" },
    { code: "ET", name: "Ethiopia", currency: "ETB", flag: "🇪🇹", symbol: "Br" },
    { code: "FJ", name: "Fiji", currency: "FJD", flag: "🇫🇯", symbol: "$" },
    { code: "FI", name: "Finland", currency: "EUR", flag: "🇫🇮", symbol: "€" },
    { code: "FR", name: "France", currency: "EUR", flag: "🇫🇷", symbol: "€" },
    { code: "GA", name: "Gabon", currency: "XAF", flag: "🇬🇦", symbol: "Fr" },
    { code: "GM", name: "Gambia", currency: "GMD", flag: "🇬🇲", symbol: "D" },
    { code: "GE", name: "Georgia", currency: "GEL", flag: "🇬🇪", symbol: "₾" },
    { code: "DE", name: "Germany", currency: "EUR", flag: "🇩🇪", symbol: "€" },
    { code: "GH", name: "Ghana", currency: "GHS", flag: "🇬🇭", symbol: "₵" },
    { code: "GR", name: "Greece", currency: "EUR", flag: "🇬🇷", symbol: "€" },
    { code: "GD", name: "Grenada", currency: "XCD", flag: "🇬🇩", symbol: "$" },
    { code: "GT", name: "Guatemala", currency: "GTQ", flag: "🇬🇹", symbol: "Q" },
    { code: "GN", name: "Guinea", currency: "GNF", flag: "🇬🇳", symbol: "Fr" },
    { code: "GW", name: "Guinea-Bissau", currency: "XOF", flag: "🇬🇼", symbol: "Fr" },
    { code: "GY", name: "Guyana", currency: "GYD", flag: "🇬🇾", symbol: "$" },
    { code: "HT", name: "Haiti", currency: "HTG", flag: "🇭🇹", symbol: "G" },
    { code: "HN", name: "Honduras", currency: "HNL", flag: "🇭🇳", symbol: "L" },
    { code: "HU", name: "Hungary", currency: "HUF", flag: "🇭🇺", symbol: "Ft" },
    { code: "IS", name: "Iceland", currency: "ISK", flag: "🇮🇸", symbol: "kr" },
    { code: "IN", name: "India", currency: "INR", flag: "🇮🇳", symbol: "₹" },
    { code: "ID", name: "Indonesia", currency: "IDR", flag: "🇮🇩", symbol: "Rp" },
    { code: "IR", name: "Iran", currency: "IRR", flag: "🇮🇷", symbol: "﷼" },
    { code: "IQ", name: "Iraq", currency: "IQD", flag: "🇮🇶", symbol: "ع.د" },
    { code: "IE", name: "Ireland", currency: "EUR", flag: "🇮🇪", symbol: "€" },
    { code: "IL", name: "Israel", currency: "ILS", flag: "🇮🇱", symbol: "₪" },
    { code: "IT", name: "Italy", currency: "EUR", flag: "🇮🇹", symbol: "€" },
    { code: "JM", name: "Jamaica", currency: "JMD", flag: "🇯🇲", symbol: "$" },
    { code: "JP", name: "Japan", currency: "JPY", flag: "🇯🇵", symbol: "¥" },
    { code: "JO", name: "Jordan", currency: "JOD", flag: "🇯🇴", symbol: "د.ا" },
    { code: "KZ", name: "Kazakhstan", currency: "KZT", flag: "🇰🇿", symbol: "₸" },
    { code: "KE", name: "Kenya", currency: "KES", flag: "🇰🇪", symbol: "KSh" },
    { code: "KI", name: "Kiribati", currency: "AUD", flag: "🇰🇮", symbol: "$" },
    { code: "KW", name: "Kuwait", currency: "KWD", flag: "🇰🇼", symbol: "د.ك" },
    { code: "KG", name: "Kyrgyzstan", currency: "KGS", flag: "🇰🇬", symbol: "с" },
    { code: "LA", name: "Laos", currency: "LAK", flag: "🇱🇦", symbol: "₭" },
    { code: "LV", name: "Latvia", currency: "EUR", flag: "🇱🇻", symbol: "€" },
    { code: "LB", name: "Lebanon", currency: "LBP", flag: "🇱🇧", symbol: "ل.ل" },
    { code: "LS", name: "Lesotho", currency: "LSL", flag: "🇱🇸", symbol: "L" },
    { code: "LR", name: "Liberia", currency: "LRD", flag: "🇱🇷", symbol: "$" },
    { code: "LY", name: "Libya", currency: "LYD", flag: "🇱🇾", symbol: "ل.د" },
    { code: "LI", name: "Liechtenstein", currency: "CHF", flag: "🇱🇮", symbol: "Fr" },
    { code: "LT", name: "Lithuania", currency: "EUR", flag: "🇱🇹", symbol: "€" },
    { code: "LU", name: "Luxembourg", currency: "EUR", flag: "🇱🇺", symbol: "€" },
    { code: "MG", name: "Madagascar", currency: "MGA", flag: "🇲🇬", symbol: "Ar" },
    { code: "MW", name: "Malawi", currency: "MWK", flag: "🇲🇼", symbol: "MK" },
    { code: "MY", name: "Malaysia", currency: "MYR", flag: "🇲🇾", symbol: "RM" },
    { code: "MV", name: "Maldives", currency: "MVR", flag: "🇲🇻", symbol: ".ރ" },
    { code: "ML", name: "Mali", currency: "XOF", flag: "🇲🇱", symbol: "Fr" },
    { code: "MT", name: "Malta", currency: "EUR", flag: "🇲🇹", symbol: "€" },
    { code: "MH", name: "Marshall Islands", currency: "USD", flag: "🇲🇭", symbol: "$" },
    { code: "MR", name: "Mauritania", currency: "MRU", flag: "🇲🇷", symbol: "UM" },
    { code: "MU", name: "Mauritius", currency: "MUR", flag: "🇲🇺", symbol: "₨" },
    { code: "MX", name: "Mexico", currency: "MXN", flag: "🇲🇽", symbol: "$" },
    { code: "FM", name: "Micronesia", currency: "USD", flag: "🇫🇲", symbol: "$" },
    { code: "MD", name: "Moldova", currency: "MDL", flag: "🇲🇩", symbol: "L" },
    { code: "MC", name: "Monaco", currency: "EUR", flag: "🇲🇨", symbol: "€" },
    { code: "MN", name: "Mongolia", currency: "MNT", flag: "🇲🇳", symbol: "₮" },
    { code: "ME", name: "Montenegro", currency: "EUR", flag: "🇲🇪", symbol: "€" },
    { code: "MA", name: "Morocco", currency: "MAD", flag: "🇲🇦", symbol: "د.م." },
    { code: "MZ", name: "Mozambique", currency: "MZN", flag: "🇲🇿", symbol: "MT" },
    { code: "MM", name: "Myanmar", currency: "MMK", flag: "🇲🇲", symbol: "Ks" },
    { code: "NA", name: "Namibia", currency: "NAD", flag: "🇳🇦", symbol: "$" },
    { code: "NR", name: "Nauru", currency: "AUD", flag: "🇳🇷", symbol: "$" },
    { code: "NP", name: "Nepal", currency: "NPR", flag: "🇳🇵", symbol: "₨" },
    { code: "NL", name: "Netherlands", currency: "EUR", flag: "🇳🇱", symbol: "€" },
    { code: "NZ", name: "New Zealand", currency: "NZD", flag: "🇳🇿", symbol: "$" },
    { code: "NI", name: "Nicaragua", currency: "NIO", flag: "🇳🇮", symbol: "C$" },
    { code: "NE", name: "Niger", currency: "XOF", flag: "🇳🇪", symbol: "Fr" },
    { code: "NG", name: "Nigeria", currency: "NGN", flag: "🇳🇬", symbol: "₦" },
    { code: "KP", name: "North Korea", currency: "KPW", flag: "🇰🇵", symbol: "₩" },
    { code: "MK", name: "North Macedonia", currency: "MKD", flag: "🇲🇰", symbol: "ден" },
    { code: "NO", name: "Norway", currency: "NOK", flag: "🇳🇴", symbol: "kr" },
    { code: "OM", name: "Oman", currency: "OMR", flag: "🇴🇲", symbol: "ر.ع." },
    { code: "PK", name: "Pakistan", currency: "PKR", flag: "🇵🇰", symbol: "₨" },
    { code: "PW", name: "Palau", currency: "USD", flag: "🇵🇼", symbol: "$" },
    { code: "PS", name: "Palestine", currency: "ILS", flag: "🇵🇸", symbol: "₪" },
    { code: "PA", name: "Panama", currency: "PAB", flag: "🇵🇦", symbol: "B/." },
    { code: "PG", name: "Papua New Guinea", currency: "PGK", flag: "🇵🇬", symbol: "K" },
    { code: "PY", name: "Paraguay", currency: "PYG", flag: "🇵🇾", symbol: "₲" },
    { code: "PE", name: "Peru", currency: "PEN", flag: "🇵🇪", symbol: "S/" },
    { code: "PH", name: "Philippines", currency: "PHP", flag: "🇵🇭", symbol: "₱" },
    { code: "PL", name: "Poland", currency: "PLN", flag: "🇵🇱", symbol: "zł" },
    { code: "PT", name: "Portugal", currency: "EUR", flag: "🇵🇹", symbol: "€" },
    { code: "QA", name: "Qatar", currency: "QAR", flag: "🇶🇦", symbol: "ر.ق" },
    { code: "RO", name: "Romania", currency: "RON", flag: "🇷🇴", symbol: "lei" },
    { code: "RU", name: "Russia", currency: "RUB", flag: "🇷🇺", symbol: "₽" },
    { code: "RW", name: "Rwanda", currency: "RWF", flag: "🇷🇼", symbol: "Fr" },
    { code: "KN", name: "Saint Kitts and Nevis", currency: "XCD", flag: "🇰🇳", symbol: "$" },
    { code: "LC", name: "Saint Lucia", currency: "XCD", flag: "🇱🇨", symbol: "$" },
    { code: "VC", name: "Saint Vincent", currency: "XCD", flag: "🇻🇨", symbol: "$" },
    { code: "WS", name: "Samoa", currency: "WST", flag: "🇼🇸", symbol: "T" },
    { code: "SM", name: "San Marino", currency: "EUR", flag: "🇸🇲", symbol: "€" },
    { code: "ST", name: "Sao Tome and Principe", currency: "STN", flag: "🇸🇹", symbol: "Db" },
    { code: "SA", name: "Saudi Arabia", currency: "SAR", flag: "🇸🇦", symbol: "ر.س" },
    { code: "SN", name: "Senegal", currency: "XOF", flag: "🇸🇳", symbol: "Fr" },
    { code: "RS", name: "Serbia", currency: "RSD", flag: "🇷🇸", symbol: "дин" },
    { code: "SC", name: "Seychelles", currency: "SCR", flag: "🇸🇨", symbol: "₨" },
    { code: "SL", name: "Sierra Leone", currency: "SLL", flag: "🇸🇱", symbol: "Le" },
    { code: "SG", name: "Singapore", currency: "SGD", flag: "🇸🇬", symbol: "$" },
    { code: "SK", name: "Slovakia", currency: "EUR", flag: "🇸🇰", symbol: "€" },
    { code: "SI", name: "Slovenia", currency: "EUR", flag: "🇸🇮", symbol: "€" },
    { code: "SB", name: "Solomon Islands", currency: "SBD", flag: "🇸🇧", symbol: "$" },
    { code: "SO", name: "Somalia", currency: "SOS", flag: "🇸🇴", symbol: "Sh" },
    { code: "ZA", name: "South Africa", currency: "ZAR", flag: "🇿🇦", symbol: "R" },
    { code: "KR", name: "South Korea", currency: "KRW", flag: "🇰🇷", symbol: "₩" },
    { code: "SS", name: "South Sudan", currency: "SSP", flag: "🇸🇸", symbol: "£" },
    { code: "ES", name: "Spain", currency: "EUR", flag: "🇪🇸", symbol: "€" },
    { code: "LK", name: "Sri Lanka", currency: "LKR", flag: "🇱🇰", symbol: "₨" },
    { code: "SD", name: "Sudan", currency: "SDG", flag: "🇸🇩", symbol: "ج.س." },
    { code: "SR", name: "Suriname", currency: "SRD", flag: "🇸🇷", symbol: "$" },
    { code: "SE", name: "Sweden", currency: "SEK", flag: "🇸🇪", symbol: "kr" },
    { code: "CH", name: "Switzerland", currency: "CHF", flag: "🇨🇭", symbol: "Fr" },
    { code: "SY", name: "Syria", currency: "SYP", flag: "🇸🇾", symbol: "£" },
    { code: "TW", name: "Taiwan", currency: "TWD", flag: "🇹🇼", symbol: "$" },
    { code: "TJ", name: "Tajikistan", currency: "TJS", flag: "🇹🇯", symbol: "ЅМ" },
    { code: "TZ", name: "Tanzania", currency: "TZS", flag: "🇹🇿", symbol: "Sh" },
    { code: "TH", name: "Thailand", currency: "THB", flag: "🇹🇭", symbol: "฿" },
    { code: "TL", name: "Timor-Leste", currency: "USD", flag: "🇹🇱", symbol: "$" },
    { code: "TG", name: "Togo", currency: "XOF", flag: "🇹🇬", symbol: "Fr" },
    { code: "TO", name: "Tonga", currency: "TOP", flag: "🇹🇴", symbol: "T$" },
    { code: "TT", name: "Trinidad and Tobago", currency: "TTD", flag: "🇹🇹", symbol: "$" },
    { code: "TN", name: "Tunisia", currency: "TND", flag: "🇹🇳", symbol: "د.ت" },
    { code: "TR", name: "Turkey", currency: "TRY", flag: "🇹🇷", symbol: "₺" },
    { code: "TM", name: "Turkmenistan", currency: "TMT", flag: "🇹🇲", symbol: "m" },
    { code: "TV", name: "Tuvalu", currency: "AUD", flag: "🇹🇻", symbol: "$" },
    { code: "UG", name: "Uganda", currency: "UGX", flag: "🇺🇬", symbol: "Sh" },
    { code: "UA", name: "Ukraine", currency: "UAH", flag: "🇺🇦", symbol: "₴" },
    { code: "AE", name: "United Arab Emirates", currency: "AED", flag: "🇦🇪", symbol: "د.إ" },
    { code: "GB", name: "United Kingdom", currency: "GBP", flag: "🇬🇧", symbol: "£" },
    { code: "US", name: "United States", currency: "USD", flag: "🇺🇸", symbol: "$" },
    { code: "UY", name: "Uruguay", currency: "UYU", flag: "🇺🇾", symbol: "$" },
    { code: "UZ", name: "Uzbekistan", currency: "UZS", flag: "🇺🇿", symbol: "so'm" },
    { code: "VU", name: "Vanuatu", currency: "VUV", flag: "🇻🇺", symbol: "Vt" },
    { code: "VA", name: "Vatican City", currency: "EUR", flag: "🇻🇦", symbol: "€" },
    { code: "VE", name: "Venezuela", currency: "VES", flag: "🇻🇪", symbol: "Bs." },
    { code: "VN", name: "Vietnam", currency: "VND", flag: "🇻🇳", symbol: "₫" },
    { code: "YE", name: "Yemen", currency: "YER", flag: "🇾🇪", symbol: "﷼" },
    { code: "ZM", name: "Zambia", currency: "ZMW", flag: "🇿🇲", symbol: "ZK" },
    { code: "ZW", name: "Zimbabwe", currency: "ZWL", flag: "🇿🇼", symbol: "$" }
];

// ============ BANKS BY COUNTRY ============
const BANKS_BY_COUNTRY = {
    "NG": [
        { name: "Access Bank", code: "044" },
        { name: "Citibank", code: "023" },
        { name: "Ecobank", code: "050" },
        { name: "Fidelity Bank", code: "070" },
        { name: "First Bank", code: "011" },
        { name: "First City Monument Bank (FCMB)", code: "214" },
        { name: "Globus Bank", code: "00103" },
        { name: "Guaranty Trust Bank (GTB)", code: "058" },
        { name: "Heritage Bank", code: "030" },
        { name: "Jaiz Bank", code: "301" },
        { name: "Keystone Bank", code: "082" },
        { name: "Kuda Bank", code: "50211" },
        { name: "Moniepoint", code: "50515" },
        { name: "Opay", code: "100004" },
        { name: "PalmPay", code: "100033" },
        { name: "Polaris Bank", code: "076" },
        { name: "Providus Bank", code: "101" },
        { name: "Stanbic IBTC", code: "221" },
        { name: "Standard Chartered", code: "068" },
        { name: "Sterling Bank", code: "232" },
        { name: "SunTrust Bank", code: "100" },
        { name: "Titan Trust Bank", code: "102" },
        { name: "Union Bank", code: "032" },
        { name: "United Bank for Africa (UBA)", code: "033" },
        { name: "Unity Bank", code: "215" },
        { name: "Wema Bank", code: "035" },
        { name: "Zenith Bank", code: "057" }
    ],
    "GH": [
        { name: "Access Bank Ghana", code: "280100" },
        { name: "Agricultural Development Bank", code: "240100" },
        { name: "Bank of Africa", code: "250100" },
        { name: "CAL Bank", code: "140100" },
        { name: "Ecobank Ghana", code: "130100" },
        { name: "Fidelity Bank Ghana", code: "240200" },
        { name: "First Atlantic Bank", code: "210100" },
        { name: "GCB Bank", code: "120100" },
        { name: "GTBank Ghana", code: "230100" },
        { name: "Republic Bank Ghana", code: "150100" },
        { name: "Stanbic Bank Ghana", code: "190100" },
        { name: "Standard Chartered Ghana", code: "020100" },
        { name: "United Bank for Africa Ghana", code: "260100" },
        { name: "Zenith Bank Ghana", code: "270100" }
    ],
    "KE": [
        { name: "ABSA Bank Kenya", code: "003" },
        { name: "Bank of Africa Kenya", code: "019" },
        { name: "Cooperative Bank of Kenya", code: "011" },
        { name: "Diamond Trust Bank", code: "063" },
        { name: "Equity Bank", code: "068" },
        { name: "Family Bank", code: "070" },
        { name: "I&M Bank", code: "057" },
        { name: "KCB Bank", code: "001" },
        { name: "MPesa", code: "MPESA" },
        { name: "NCBA Bank", code: "007" },
        { name: "Sidian Bank", code: "066" },
        { name: "Standard Chartered Kenya", code: "002" },
        { name: "Stanbic Bank Kenya", code: "031" }
    ],
    "ZA": [
        { name: "ABSA Bank", code: "632005" },
        { name: "African Bank", code: "430000" },
        { name: "Capitec Bank", code: "470010" },
        { name: "Discovery Bank", code: "679000" },
        { name: "First National Bank (FNB)", code: "250655" },
        { name: "Investec", code: "580105" },
        { name: "Nedbank", code: "198765" },
        { name: "Standard Bank", code: "051001" },
        { name: "TymeBank", code: "678910" }
    ],
    "US": [
        { name: "Bank of America", code: "BOA" },
        { name: "Chase Bank", code: "CHASE" },
        { name: "Citibank", code: "CITI" },
        { name: "Goldman Sachs", code: "GS" },
        { name: "Morgan Stanley", code: "MS" },
        { name: "PNC Bank", code: "PNC" },
        { name: "TD Bank", code: "TD" },
        { name: "US Bank", code: "USB" },
        { name: "Wells Fargo", code: "WF" }
    ],
    "GB": [
        { name: "Barclays", code: "BARC" },
        { name: "HSBC UK", code: "HSBC" },
        { name: "Lloyds Bank", code: "LOYD" },
        { name: "Metro Bank", code: "METR" },
        { name: "Monzo", code: "MONZ" },
        { name: "Nationwide", code: "NAIW" },
        { name: "NatWest", code: "NWBK" },
        { name: "Revolut", code: "REVO" },
        { name: "Santander UK", code: "SANT" },
        { name: "Starling Bank", code: "STAR" },
        { name: "TSB Bank", code: "TSBS" }
    ],
    "CA": [
        { name: "BMO Bank of Montreal", code: "001" },
        { name: "CIBC", code: "010" },
        { name: "National Bank of Canada", code: "006" },
        { name: "RBC Royal Bank", code: "003" },
        { name: "Scotiabank", code: "002" },
        { name: "TD Canada Trust", code: "004" },
        { name: "Tangerine", code: "614" },
        { name: "Simplii Financial", code: "308" }
    ],
    "IN": [
        { name: "Axis Bank", code: "AXIS" },
        { name: "Bank of Baroda", code: "BARB" },
        { name: "HDFC Bank", code: "HDFC" },
        { name: "ICICI Bank", code: "ICIC" },
        { name: "Kotak Mahindra Bank", code: "KKBK" },
        { name: "Paytm Payments Bank", code: "PAYT" },
        { name: "Punjab National Bank", code: "PUNB" },
        { name: "State Bank of India (SBI)", code: "SBIN" },
        { name: "Yes Bank", code: "YESB" }
    ],
    "AE": [
        { name: "Abu Dhabi Commercial Bank", code: "ADCB" },
        { name: "Abu Dhabi Islamic Bank", code: "ADIB" },
        { name: "Dubai Islamic Bank", code: "DIB" },
        { name: "Emirates NBD", code: "ENBD" },
        { name: "First Abu Dhabi Bank", code: "FAB" },
        { name: "Mashreq Bank", code: "MASH" },
        { name: "RAK Bank", code: "RAKB" },
        { name: "Sharjah Islamic Bank", code: "SIB" }
    ]
};

// ============ Exchange Rates (USD to Local) - Updated Daily ============
const EXCHANGE_RATES = {
    "NGN": 1550, "GHS": 12.5, "KES": 145, "ZAR": 18.5, "USD": 1,
    "GBP": 0.79, "EUR": 0.92, "CAD": 1.36, "INR": 83, "AED": 3.67,
    "AUD": 1.53, "CNY": 7.24, "JPY": 149, "BRL": 5.05, "MXN": 17.2
};

// ============ App State ============
const APP_STATE = {
    currentUser: null,
    userProfile: null,
    currentScreen: 'onboarding',
    previousScreen: null,
    isAuthenticated: false,
    cart: [],
    selectedProduct: null,
    navigationHistory: [],
    selectedColor: null,
    selectedSize: null,
    productQuantity: 1,
    userCountry: null,
    userCurrency: null,
    exchangeRate: 1
};